# Generated by Django 2.0.8 on 2019-02-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='المشاهدات')),
                ('photo', models.ImageField(blank=True, upload_to='users/img/profile/%Y/%m/%d', verbose_name='صورة')),
                ('bio', models.TextField(max_length=99, verbose_name='نبذة تعريفية')),
                ('gender', models.CharField(choices=[('male', 'رجل'), ('female', 'امرأه')], max_length=6, verbose_name='النوع')),
                ('mobile', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('facebook', models.CharField(max_length=100, verbose_name='فيسبوك')),
                ('twitter', models.CharField(max_length=100, verbose_name='تويتر')),
                ('github', models.CharField(max_length=100, verbose_name='جيت هب')),
                ('whatsapp_mobile', models.CharField(max_length=20, verbose_name=' رقم الهاتف واتس اب')),
                ('prev_languages', models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('c++', 'C++'), ('c#', 'C#'), ('VB', 'VB.NET'), ('ruby', 'Ruby'), ('java', 'Java'), ('js', 'JavaScript'), ('php', 'Php'), ('django', 'Django'), ('flask', 'Flask'), ('ror', 'RubyOnRails'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'BootStrap'), ('react', 'React'), ('angular', 'Angular'), ('ring', 'Ring')], max_length=8, verbose_name='اللغة المفضلة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الصفحة الشخصية',
                'verbose_name_plural': 'الصفحات الشخصية',
            },
        ),
    ]
