# Generated by Django 2.0.8 on 2019-02-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190216_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_articles',
            field=models.PositiveIntegerField(default=0, verbose_name='قرآءةالمقالات'),
        ),
    ]
