# Generated by Django 2.0.8 on 2019-02-16 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import track.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('views', models.PositiveIntegerField(verbose_name='المشاهدات')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'القسم',
                'ordering': ('title',),
                'verbose_name_plural': 'الاقسام',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', track.fields.OrderField(blank=True, verbose_name='الترتيب')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('text', 'video', 'image', 'file')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='النوع')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('overview', models.TextField(blank=True, verbose_name='المقدمة')),
                ('image', models.ImageField(blank=True, upload_to='courses/img/%Y/%m/%d', verbose_name='صورة')),
            ],
            options={
                'verbose_name': 'كورس',
                'ordering': ('-created_at',),
                'verbose_name_plural': 'كورسات',
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='track.Course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'عضو مشترك',
                'verbose_name_plural': 'المشتركين',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('file', models.FileField(upload_to='content/files', verbose_name='الملف')),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'الملفات',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('file', models.ImageField(blank=True, upload_to='content/images/%Y/%m/%d', verbose_name='صورة')),
            ],
            options={
                'verbose_name': 'صورة',
                'verbose_name_plural': 'الصور',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('views', models.PositiveIntegerField(verbose_name='المشاهدات')),
                ('order', track.fields.OrderField(blank=True, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'محاضرة',
                'ordering': ['order'],
                'verbose_name_plural': 'المحاضرات',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='track.Category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'التمارين',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('content', models.TextField(verbose_name='المحتوي')),
            ],
            options={
                'verbose_name': 'نص',
                'verbose_name_plural': 'المحتوي النصي',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('image', models.ImageField(blank=True, upload_to='tracks/img/%Y/%m/%d', verbose_name='صورة')),
                ('articles', models.ManyToManyField(related_name='track', to='track.Article', verbose_name='مقالات')),
                ('courses', models.ManyToManyField(related_name='track', to='track.Course', verbose_name='الكورسات')),
                ('practices', models.ManyToManyField(related_name='track', to='track.Practice', verbose_name='تمارين')),
            ],
            options={
                'verbose_name': 'مسار',
                'verbose_name_plural': 'مسارات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('content', models.TextField(blank=True, verbose_name='المحتوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='الحالة')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('img', models.ImageField(blank=True, upload_to='courses/unit/img/%Y/%m/%d', verbose_name='صورة')),
                ('order', track.fields.OrderField(blank=True, verbose_name='الترتيب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='track.Course', verbose_name='الكورس')),
            ],
            options={
                'verbose_name': 'الوحدة',
                'ordering': ['order'],
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل في')),
                ('url', models.URLField(verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'فديو',
                'verbose_name_plural': 'الفديوهات',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='track.Unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ManyToManyField(related_name='courses', through='track.CourseMember', to='accounts.Profile', verbose_name='المستخدمين'),
        ),
        migrations.AddField(
            model_name='content',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='track.Lecture', verbose_name='المحاضرة'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='track.Category', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course', 'profile')},
        ),
    ]
