# Generated by Django 2.0.8 on 2019-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'محتوي', 'verbose_name_plural': 'المحتويات'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'نص', 'verbose_name_plural': 'النصوص'},
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='المشاهدات'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='المشاهدات'),
        ),
    ]
