# Generated by Django 2.0.8 on 2019-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20190216_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='last_lecture',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
