# Generated by Django 2.2 on 2019-04-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_course_joines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='track',
            name='image',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='img',
        ),
    ]
